<a href="https://colab.research.google.com/github/suubkiim/Pytorch-practice/blob/master/NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms


# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hyper-parameters 
input_size = 784
hidden_size = 500
num_classes = 10
num_epochs = 5
batch_size = 100
learning_rate = 0.001

# MNIST dataset 
train_dataset = torchvision.datasets.MNIST(root='../../data', 
                                           train=True, 
                                           transform=transforms.ToTensor(),  
                                           download=True)

test_dataset = torchvision.datasets.MNIST(root='../../data', 
                                          train=False, 
                                          transform=transforms.ToTensor())

# Data loader
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, 
                                           batch_size=batch_size, 
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset, 
                                          batch_size=batch_size, 
                                          shuffle=False)

# Fully connected neural network with one hidden layer
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)  
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

model = NeuralNet(input_size, hidden_size, num_classes).to(device) #GPU 상에 tensor 올리기

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)  

# Train the model
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):  
        # Move tensors to the configured device
        images = images.reshape(-1, 28*28).to(device)
        labels = labels.to(device)
        
        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))

# Test the model
# In test phase, we don't need to compute gradients (for memory efficiency)
with torch.no_grad(): 
  # "with torch.no_grad()" temporarily set all the requires_grad flag to false.
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, 28*28).to(device)
        labels = labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Accuracy of the network on the 10000 test images: {} %'.format(100 * correct / total))

# Save the model checkpoint
torch.save(model.state_dict(), 'model.ckpt')

0it [00:00, ?it/s]

9920512it [00:05, 1815598.82it/s]                             


Extracting ../../data/MNIST/raw/train-images-idx3-ubyte.gz to ../../data/MNIST/raw


32768it [00:00, 456057.82it/s]
  2%|▏         | 40960/1648877 [00:00<00:04, 393294.92it/s]

Extracting ../../data/MNIST/raw/train-labels-idx1-ubyte.gz to ../../data/MNIST/raw


1654784it [00:00, 8199320.20it/s]                          
8192it [00:00, 173598.91it/s]


Extracting ../../data/MNIST/raw/t10k-images-idx3-ubyte.gz to ../../data/MNIST/raw
Extracting ../../data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ../../data/MNIST/raw
Processing...
Done!
Epoch [1/5], Step [100/600], Loss: 0.2019
Epoch [1/5], Step [200/600], Loss: 0.2757
Epoch [1/5], Step [300/600], Loss: 0.2643
Epoch [1/5], Step [400/600], Loss: 0.2319
Epoch [1/5], Step [500/600], Loss: 0.1339
Epoch [1/5], Step [600/600], Loss: 0.0551
Epoch [2/5], Step [100/600], Loss: 0.1692
Epoch [2/5], Step [200/600], Loss: 0.1456
Epoch [2/5], Step [300/600], Loss: 0.0844
Epoch [2/5], Step [400/600], Loss: 0.1757
Epoch [2/5], Step [500/600], Loss: 0.0530
Epoch [2/5], Step [600/600], Loss: 0.0459
Epoch [3/5], Step [100/600], Loss: 0.2044
Epoch [3/5], Step [200/600], Loss: 0.0329
Epoch [3/5], Step [300/600], Loss: 0.0847
Epoch [3/5], Step [400/600], Loss: 0.0684
Epoch [3/5], Step [500/600], Loss: 0.1206
Epoch [3/5], Step [600/600], Loss: 0.0627
Epoch [4/5], Step [100/600], Loss: 0.1668
Epoch [4/5], Step 

In [0]:
outputs

tensor([[-6.2397e+00, -6.2180e+00, -3.1514e+00, -1.9297e+00, -6.4638e+00,
         -1.6653e+00, -2.5305e+00, -1.3265e+01,  7.2539e+00, -5.9990e+00],
        [-9.8969e+00, -9.6303e+00, -7.6915e+00, -4.1374e+00, -1.0254e+00,
         -6.0836e+00, -1.0263e+01, -6.3374e+00, -5.3826e-01,  6.3873e+00],
        [ 8.8627e+00, -9.8486e+00, -2.1724e+00, -2.0335e+00, -6.4434e+00,
         -2.2794e+00, -1.4468e+00, -9.6537e+00,  2.3702e-01, -1.1400e+00],
        [-1.0701e+01,  4.3689e+00, -4.9370e+00, -4.4636e+00, -2.8598e+00,
         -1.1463e+01, -7.5469e+00, -1.4878e+00, -9.8878e-01, -6.2715e+00],
        [ 8.0301e-01, -7.7234e+00, -1.3271e+00,  1.0072e+00, -6.7226e+00,
         -2.1192e+00, -2.0266e+00, -7.0467e+00, -1.6718e+00, -6.7120e+00],
        [-6.9894e+00, -7.9172e+00, -2.2269e+00,  5.5662e+00, -1.1458e+01,
         -1.0043e+01, -1.3078e+01, -5.4106e-01,  1.5987e-01, -3.6688e-01],
        [-1.0720e+00, -6.3800e+00, -1.9282e-01, -4.3910e+00,  4.0175e+00,
         -6.3851e+00, -2.1640e+0

In [0]:
_,predicted=torch.max(outputs.data, 1)

In [0]:
_

tensor([ 7.2539,  6.3873,  8.8627,  4.3689,  1.0072,  5.5662,  4.0175,  7.4325,
         9.4001,  7.9375,  4.7261, 10.8517,  7.0584,  7.2103,  7.5874,  7.0138,
         4.3719, 10.0036,  6.7481,  7.7702,  9.8009,  5.2528,  3.7001,  6.7938,
         6.7643,  4.8809,  4.5888,  4.6534,  6.8706,  5.4344, 10.6075,  6.4376,
         8.3222, 10.6785, 10.0182,  6.3814,  9.7183,  9.5477,  8.5363, 11.3067,
         4.5015,  2.1305, 12.3572,  5.8522,  4.5110,  6.8755,  5.5015,  9.6926,
         8.8919,  9.4185,  6.1465,  8.5108, 13.7277,  4.9332,  7.9741,  5.7012,
         5.6016,  6.3276,  6.7585,  4.8019, 11.0431,  8.0809,  8.5246,  6.4642,
         7.3807,  9.9228,  8.9543,  7.6403, 10.0388,  6.1455,  9.4842,  6.9199,
        11.4643,  9.0374,  8.7384,  4.2994,  4.6615,  5.5385,  6.0892,  8.0524,
         8.6804,  6.3935,  3.0294, 17.4045,  5.9790, 12.3286,  6.9513, 11.5299,
        13.9453, 11.4954,  9.2685, 13.0880,  9.2801, 10.0262,  5.9862, 15.8145,
        10.9299, 10.0406, 12.0567, 12.87

In [0]:
predicted

tensor([8, 9, 0, 1, 3, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 7, 8, 9, 7, 8, 6, 4, 1,
        9, 3, 8, 4, 4, 7, 0, 1, 9, 2, 8, 7, 8, 2, 6, 0, 6, 5, 3, 3, 8, 9, 1, 4,
        0, 6, 1, 0, 0, 6, 2, 1, 1, 7, 7, 8, 4, 6, 0, 7, 0, 3, 6, 8, 7, 1, 5, 2,
        4, 9, 4, 3, 6, 4, 1, 7, 2, 6, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2,
        3, 4, 5, 6], device='cuda:0')